# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Repository-Query' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Repository-Query
  pod 'Alamofire'
  pod "MarkdownView"
  
  target 'Repository-QueryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Repository-QueryUITests' do
    # Pods for testing
  end

end
